// Generated by scripts/convert-materials.ts from v1 materials (S8-02). Edit
// titles here; page text lives in the .mdx files next to this one.
import type { MaterialCatalog } from "@/features/materials/domain/types";

export const catalog: MaterialCatalog = [
  {
    grade: 10,
    chapters: [
      {
        slug: "chuyen-dong",
        title: "Chuyển động và Động học",
        description: "Mô tả chuyển động của vật",
        topics: [
          {
            slug: "chuyen-dong-thang-deu",
            title: "Chuyển động thẳng đều",
            description:
              "Tốc độ trung bình của một vật được định nghĩa bằng thương số giữa quãng đường đi được và thời gian để đi hết quãng đường đó.",
            subtopics: [
              "Vận tốc",
              "Quãng đường",
              "Phương trình chuyển động",
              "Đồ thị",
            ],
            legacyPath: "grade10/motion_kinematics/chuyen_dong_thang_deu",
          },
          {
            slug: "chuyen-dong-bien-doi-deu",
            title: "Chuyển động thẳng biến đổi đều",
            description:
              "Vận tốc tức thời tại một thời điểm là đại lượng đặc trưng cho chiều và độ nhanh chậm của chuyển động tại thời điểm đó.",
            subtopics: [
              "Gia tốc",
              "Công thức chuyển động",
              "Nhanh dần đều",
              "Chậm dần đều",
            ],
            legacyPath: "grade10/motion_kinematics/chuyen_dong_bien_doi_deu",
          },
          {
            slug: "roi-tu-do",
            title: "Sự rơi tự do",
            description:
              "Tại một nơi trên Trái Đất và ở gần mặt đất, mọi vật đều rơi tự do với cùng một gia tốc g.",
            subtopics: ["Gia tốc trọng trường", "Thả rơi", "Ném thẳng đứng"],
            legacyPath: "grade10/motion_kinematics/roi_tu_do",
          },
          {
            slug: "chuyen-dong-tron-deu",
            title: "Chuyển động tròn đều",
            description:
              "Tốc độ dài là độ lớn của vận tốc tức thời trong chuyển động tròn.",
            subtopics: ["Tốc độ góc", "Chu kỳ", "Tần số", "Gia tốc hướng tâm"],
            legacyPath: "grade10/motion_kinematics/chuyen_dong_tron_deu",
          },
          {
            slug: "tinh-tuong-doi-cua-chuyen-dong",
            title: "Tính tương đối của chuyển động",
            description: "Tính tương đối của chuyển động",
            subtopics: [],
            legacyPath:
              "grade10/motion_kinematics/tinh_tuong_doi_cua_chuyen_dong",
          },
        ],
        links: [],
      },
      {
        slug: "luc-va-dong-luc-hoc",
        title: "Lực và Động lực học",
        description: "Nguyên nhân gây ra chuyển động",
        topics: [
          {
            slug: "luc-va-dinh-luat-newton",
            title: "Lực và Ba định luật Newton",
            description: "Lực và Ba định luật Newton",
            subtopics: [
              "Định luật I Newton",
              "Định luật II Newton",
              "Định luật III Newton",
              "Phương pháp giải",
            ],
            legacyPath: "grade10/forces_dynamics/luc_va_dinh_luat_newton",
          },
          {
            slug: "cac-loai-luc",
            title: "Các loại lực",
            description: "Các loại lực",
            subtopics: [
              "Trọng lực",
              "Lực ma sát",
              "Lực đàn hồi",
              "Lực hướng tâm",
              "Lực căng dây",
            ],
            legacyPath: "grade10/forces_dynamics/cac_loai_luc",
          },
        ],
        links: [],
      },
      {
        slug: "nang-luong",
        title: "Năng lượng",
        description: "Công, công suất và các dạng năng lượng",
        topics: [
          {
            slug: "cong-va-cong-suat",
            title: "Công và Công suất",
            description: "Công và Công suất",
            subtopics: ["Công cơ học", "Công suất", "Hiệu suất"],
            legacyPath: "grade10/energy/cong_va_cong_suat",
          },
          {
            slug: "dong-nang-the-nang",
            title: "Động năng và Thế năng",
            description: "Động năng và Thế năng",
            subtopics: [
              "Động năng",
              "Thế năng trọng trường",
              "Thế năng đàn hồi",
              "Định lý động năng",
            ],
            legacyPath: "grade10/energy/dong_nang_the_nang",
          },
          {
            slug: "co-nang-bao-toan",
            title: "Cơ năng và Định luật bảo toàn",
            description:
              "Cơ năng có đơn vị là Jun (J), giống như động năng và thế năng.",
            subtopics: ["Cơ năng", "Bảo toàn cơ năng", "Biến đổi năng lượng"],
            legacyPath: "grade10/energy/co_nang_bao_toan",
          },
        ],
        links: [],
      },
      {
        slug: "dong-luong",
        title: "Động lượng",
        description: "Động lượng và các định luật bảo toàn",
        topics: [
          {
            slug: "dong-luong-xung-luong",
            title: "Động lượng và Xung lượng",
            description: "Động lượng và Xung lượng",
            subtopics: [
              "Khái niệm động lượng",
              "Xung lượng của lực",
              "Định lý động lượng - xung lượng",
            ],
            legacyPath: "grade10/momentum/dong_luong_xung_luong",
          },
          {
            slug: "bao-toan-dong-luong",
            title: "Định luật bảo toàn động lượng",
            description: "Định luật bảo toàn động lượng",
            subtopics: [
              "Hệ kín",
              "Bảo toàn động lượng",
              "Chuyển động phản lực",
              "Nổ và bắn",
            ],
            legacyPath: "grade10/momentum/bao_toan_dong_luong",
          },
          {
            slug: "va-cham",
            title: "Va chạm",
            description: "Va chạm",
            subtopics: [
              "Va chạm đàn hồi",
              "Va chạm không đàn hồi",
              "Va chạm mềm",
              "Con lắc thử đạn",
            ],
            legacyPath: "grade10/momentum/va_cham",
          },
        ],
        links: [],
      },
    ],
  },
  {
    grade: 11,
    chapters: [
      {
        slug: "dao-dong",
        title: "Dao động",
        description: "Dao động điều hòa, con lắc lò xo, con lắc đơn",
        topics: [
          {
            slug: "bai-1-dao-dong-dieu-hoa",
            title: "Dao động điều hòa",
            description:
              "Dao động điều hòa là một trong những chuyển động cơ bản nhất trong vật lý. Tìm hiểu về phương trình, đồ thị và các đại lượng đặc trưng của dao động điều hòa.",
            subtopics: [
              "Phương trình dao động",
              "Chu kỳ",
              "Tần số",
              "Vận tốc",
              "Gia tốc",
            ],
            legacyPath: "grade11/dao-dong/bai-1-dao-dong-dieu-hoa",
          },
          {
            slug: "bai-2-con-lac-lo-xo",
            title: "Con lắc lò xo",
            description:
              "Con lắc lò xo là hệ dao động điều hòa điển hình. Tìm hiểu về cấu tạo, phương trình dao động, chu kỳ, năng lượng và các bài tập về con lắc lò xo.",
            subtopics: [
              "Lực kéo về",
              "Năng lượng",
              "Con lắc treo",
              "Con lắc ngang",
            ],
            legacyPath: "grade11/dao-dong/bai-2-con-lac-lo-xo",
          },
          {
            slug: "bai-3-con-lac-don",
            title: "Con lắc đơn",
            description:
              "Con lắc đơn là hệ dao động quan trọng trong vật lý. Tìm hiểu về cấu tạo, phương trình dao động, chu kỳ và các ứng dụng của con lắc đơn.",
            subtopics: [
              "Chu kỳ con lắc",
              "Phương trình dao động",
              "Năng lượng",
              "Ứng dụng",
            ],
            legacyPath: "grade11/dao-dong/bai-3-con-lac-don",
          },
          {
            slug: "bai-4-tong-hop-dao-dong",
            title: "Tổng hợp dao động",
            description:
              "Tổng hợp dao động điều hòa cùng phương cùng tần số. Phương pháp giản đồ Fresnel và các trường hợp đặc biệt trong tổng hợp dao động.",
            subtopics: [
              "Phương pháp giản đồ",
              "Cùng phương",
              "Cùng tần số",
              "Độ lệch pha",
            ],
            legacyPath: "grade11/dao-dong/bai-4-tong-hop-dao-dong",
          },
        ],
        links: [],
      },
      {
        slug: "song",
        title: "Sóng",
        description: "Sóng cơ, sóng âm, giao thoa sóng, sóng dừng",
        topics: [
          {
            slug: "bai-1-song-co-va-su-truyen-song",
            title: "Sóng cơ và sự truyền sóng",
            description:
              "Sóng cơ học là dao động lan truyền trong môi trường vật chất. Tìm hiểu về khái niệm, phân loại, các đại lượng đặc trưng và phương trình sóng.",
            subtopics: [
              "Bước sóng",
              "Tần số sóng",
              "Vận tốc truyền sóng",
              "Phương trình sóng",
            ],
            legacyPath: "grade11/song/bai-1-song-co-va-su-truyen-song",
          },
          {
            slug: "bai-2-giao-thoa-song",
            title: "Giao thoa sóng",
            description:
              "Giao thoa sóng là hiện tượng đặc trưng của sóng. Tìm hiểu về điều kiện giao thoa, vân giao thoa và các bài toán liên quan.",
            subtopics: [
              "Hai nguồn kết hợp",
              "Cực đại",
              "Cực tiểu",
              "Vân giao thoa",
            ],
            legacyPath: "grade11/song/bai-2-giao-thoa-song",
          },
          {
            slug: "bai-3-song-dung",
            title: "Sóng dừng",
            description:
              "Sóng dừng là kết quả giao thoa của sóng tới và sóng phản xạ. Tìm hiểu về điều kiện sóng dừng, nút, bụng sóng và ứng dụng trong nhạc cụ.",
            subtopics: [
              "Nút sóng",
              "Bụng sóng",
              "Điều kiện sóng dừng",
              "Ứng dụng",
            ],
            legacyPath: "grade11/song/bai-3-song-dung",
          },
          {
            slug: "bai-4-song-am",
            title: "Sóng âm",
            description:
              "Sóng âm là sóng cơ lan truyền trong môi trường vật chất. Tìm hiểu về đặc trưng vật lý và sinh lý của âm thanh, cường độ âm và các ứng dụng.",
            subtopics: [
              "Đặc trưng âm",
              "Cường độ âm",
              "Mức cường độ âm",
              "Nguồn âm",
            ],
            legacyPath: "grade11/song/bai-4-song-am",
          },
        ],
        links: [],
      },
      {
        slug: "dien-truong",
        title: "Điện trường",
        description: "Điện tích, điện trường, điện thế, tụ điện",
        topics: [
          {
            slug: "bai-1-dien-tich-dinh-luat-coulomb",
            title: "Điện tích - Định luật Coulomb",
            description:
              "Điện tích và định luật Coulomb là nền tảng của điện học. Tìm hiểu về các loại điện tích, sự tương tác và định luật Coulomb trong vật lý 11.",
            subtopics: [
              "Điện tích",
              "Lực Coulomb",
              "Nguyên lý chồng chất",
              "Hằng số điện môi",
            ],
            legacyPath: "grade11/dien-truong/bai-1-dien-tich-dinh-luat-coulomb",
          },
          {
            slug: "bai-2-dien-truong-cuong-do-dien-truong",
            title: "Điện trường và cường độ điện trường",
            description:
              "Điện trường là môi trường vật chất đặc biệt bao quanh điện tích. Tìm hiểu về khái niệm, cường độ điện trường và đường sức điện.",
            subtopics: [
              "Cường độ điện trường",
              "Đường sức",
              "Điện trường đều",
              "Nguyên lý chồng chất",
            ],
            legacyPath:
              "grade11/dien-truong/bai-2-dien-truong-cuong-do-dien-truong",
          },
          {
            slug: "bai-3-dien-the-hieu-dien-the",
            title: "Điện thế - Hiệu điện thế",
            description:
              "Điện thế và hiệu điện thế là khái niệm quan trọng trong điện học. Tìm hiểu về công của lực điện, điện thế, hiệu điện thế và mối liên hệ với cường độ điện trường.",
            subtopics: [
              "Công của lực điện",
              "Điện thế",
              "Hiệu điện thế",
              "Liên hệ E và U",
            ],
            legacyPath: "grade11/dien-truong/bai-3-dien-the-hieu-dien-the",
          },
          {
            slug: "bai-4-tu-dien",
            title: "Tụ điện",
            description:
              "Tụ điện là linh kiện điện tử quan trọng. Tìm hiểu về cấu tạo, điện dung, cách ghép tụ điện và năng lượng điện trường trong tụ điện.",
            subtopics: [
              "Điện dung",
              "Ghép tụ điện",
              "Năng lượng tụ điện",
              "Ứng dụng",
            ],
            legacyPath: "grade11/dien-truong/bai-4-tu-dien",
          },
        ],
        links: [],
      },
      {
        slug: "dong-dien",
        title: "Dòng điện",
        description: "Dòng điện không đổi, dòng điện trong các môi trường",
        topics: [
          {
            slug: "bai-1-dong-dien-khong-doi",
            title: "Dòng điện không đổi",
            description:
              "Dòng điện không đổi là nền tảng của điện học. Tìm hiểu về bản chất dòng điện, cường độ dòng điện và các khái niệm cơ bản về mạch điện.",
            subtopics: [
              "Cường độ dòng điện",
              "Điện lượng",
              "Chiều dòng điện",
              "Tác dụng",
            ],
            legacyPath: "grade11/dong-dien/bai-1-dong-dien-khong-doi",
          },
          {
            slug: "bai-2-dien-tro-dinh-luat-ohm",
            title: "Điện trở - Định luật Ohm",
            description:
              "Điện trở và định luật Ohm là kiến thức cốt lõi về mạch điện. Tìm hiểu về điện trở, định luật Ohm, cách ghép điện trở và ứng dụng thực tế.",
            subtopics: [
              "Định luật Ohm",
              "Điện trở",
              "Ghép điện trở",
              "Điện trở suất",
            ],
            legacyPath: "grade11/dong-dien/bai-2-dien-tro-dinh-luat-ohm",
          },
          {
            slug: "bai-3-nguon-dien",
            title: "Nguồn điện",
            description:
              "Nguồn điện là thiết bị tạo và duy trì hiệu điện thế. Tìm hiểu về suất điện động, điện trở trong, định luật Ohm toàn mạch và cách ghép nguồn điện.",
            subtopics: [
              "Suất điện động",
              "Điện trở trong",
              "Ghép nguồn",
              "Hiệu suất",
            ],
            legacyPath: "grade11/dong-dien/bai-3-nguon-dien",
          },
          {
            slug: "bai-4-dong-dien-trong-cac-moi-truong",
            title: "Dòng điện trong các môi trường",
            description:
              "Dòng điện trong kim loại, chất điện phân, chất khí và chân không. Tìm hiểu bản chất, định luật và ứng dụng của dòng điện trong các môi trường khác nhau.",
            subtopics: ["Kim loại", "Chất điện phân", "Chất khí", "Chân không"],
            legacyPath:
              "grade11/dong-dien/bai-4-dong-dien-trong-cac-moi-truong",
          },
        ],
        links: [],
      },
    ],
  },
  {
    grade: 12,
    chapters: [
      {
        slug: "dao-dong-co",
        title: "Dao động cơ",
        description:
          "Dao động điều hòa, Con lắc lò xo, Con lắc đơn, Dao động tắt dần, dao động cưỡng bức",
        topics: [
          {
            slug: "bai-1-dao-dong-dieu-hoa",
            title: "Dao động điều hòa",
            description:
              "Dao động điều hòa là một trong những dạng dao động cơ bản nhất trong vật lý. Tìm hiểu chi tiết về phương trình, đồ thị và các đại lượng đặc trưng của dao động điều hòa.",
            subtopics: [
              "Phương trình dao động",
              "Li độ, vận tốc, gia tốc",
              "Chu kỳ, tần số",
              "Đồ thị dao động",
            ],
            legacyPath: "grade12/dao-dong-co/bai-1-dao-dong-dieu-hoa",
          },
          {
            slug: "bai-2-con-lac-lo-xo",
            title: "Con lắc lò xo",
            description:
              "Con lắc lò xo là hệ dao động điều hòa điển hình trong vật lý. Tìm hiểu chi tiết về cấu tạo, phương trình dao động, chu kỳ và năng lượng của con lắc lò xo.",
            subtopics: [
              "Chu kỳ, tần số",
              "Năng lượng dao động",
              "Con lắc treo thẳng đứng",
              "Con lắc ngang",
            ],
            legacyPath: "grade12/dao-dong-co/bai-2-con-lac-lo-xo",
          },
          {
            slug: "bai-3-con-lac-don",
            title: "Con lắc đơn",
            description:
              "Con lắc đơn là hệ dao động cơ học quan trọng. Tìm hiểu về cấu tạo, điều kiện dao động điều hòa, chu kỳ và ứng dụng của con lắc đơn trong thực tế.",
            subtopics: [
              "Phương trình dao động",
              "Chu kỳ con lắc đơn",
              "Năng lượng con lắc",
              "Con lắc vật lý",
            ],
            legacyPath: "grade12/dao-dong-co/bai-3-con-lac-don",
          },
          {
            slug: "bai-4-dao-dong-tat-dan-cuong-buc",
            title: "Dao động tắt dần, dao động cưỡng bức",
            description:
              "Tìm hiểu về dao động tắt dần, dao động cưỡng bức và hiện tượng cộng hưởng. Các ứng dụng thực tế của dao động tắt dần và cộng hưởng trong đời sống.",
            subtopics: [
              "Dao động tắt dần",
              "Dao động duy trì",
              "Dao động cưỡng bức",
              "Hiện tượng cộng hưởng",
            ],
            legacyPath: "grade12/dao-dong-co/bai-4-dao-dong-tat-dan-cuong-buc",
          },
        ],
        links: [
          {
            title: "Lý thuyết cơ bản chương dao động cơ, vật lí 12",
            url: "https://vatlypt.com/ly-thuyet-co-ban-chuong-dao-dong-co-vat-li-12.html",
            group: "Lý thuyết",
          },
          {
            title: "Lý thuyết cơ bản DAO ĐỘNG ĐIỀU HÒA - HOCMAI",
            url: "https://hocmai.vn/kho-tai-lieu/read.php?id=616",
            group: "Lý thuyết",
          },
          {
            title: "Con lắc lò xo treo thẳng đứng",
            url: "https://vatlypt.com/con-lac-lo-xo-treo-thang-dung.html",
            group: "Lý thuyết",
          },
          {
            title: "Con lắc đơn dao động điều hòa, vật lí 11",
            url: "https://vatlypt.com/con-lac-don-dao-dong-dieu-hoa-vat-li-11.html",
            group: "Lý thuyết",
          },
          {
            title: "Vật lý 12 Bài 4: Dao động tắt dần và dao động cưỡng bức",
            url: "https://hoc247.net/vat-ly-12/bai-4-dao-dong-tat-dan-va-dao-dong-cuong-buc-l1055.html",
            group: "Lý thuyết",
          },
          {
            title: "TÓM TẮT CÔNG THỨC VẬT LÍ 12 - HOCMAI",
            url: "https://hocmai.vn/kho-tai-lieu/read.php?id=3118",
            group: "Công thức",
          },
          {
            title: "Tóm tắt công thức Vật Lí 12 theo chuyên đề - HOCMAI",
            url: "https://hocmai.vn/kho-tai-lieu/read.php?id=960",
            group: "Công thức",
          },
          {
            title: "Công thức Năng lượng con lắc lò xo, vật lí 12",
            url: "https://vatlypt.com/cong-thuc-nang-luong-con-lac-lo-xo-vat-ly-12.html",
            group: "Công thức",
          },
          {
            title: "Bài tập con lắc lò xo dao động điều hòa",
            url: "https://vatlypt.com/bai-tap-con-lac-lo-xo-dao-dong-dieu-hoa-vat-li-11.html",
            group: "Bài tập",
          },
          {
            title: "Bài tập dao động tắt dần, các loại dao động cơ",
            url: "https://vatlypt.com/d/bai-tap-dao-dong-tat-dan-cac-loai-dao-dong-co.t444.html",
            group: "Bài tập",
          },
          {
            title: "Vật lí lớp 12 lý thuyết và bài tập vận dụng",
            url: "https://vatlypt.com/vat-li-lop-12-ly-thuyet-va-bai-tap-van-dung.html",
            group: "Bài tập",
          },
          {
            title:
              "Trong dao động điều hòa của con lắc lò xo, phát biểu nào sau đây là không đúng?",
            url: "https://moon.vn/hoi-dap/trong-dao-dong-dieu-hoa-cua-con-lac-lo-xo-phat-bieu-nao-sau-day-la-khong-dung-354837",
            group: "Trắc nghiệm",
          },
          {
            title: "Trắc nghiệm lý thuyết vật lí 12",
            url: "https://vatlypt.com/trac-nghiem-ly-thuyet-vat-li-12.html",
            group: "Trắc nghiệm",
          },
          {
            title:
              "Đại lượng nào sau đây tăng gấp đôi khi tăng gấp đôi biên độ dao động điều hòa?",
            url: "https://moon.vn/hoi-dap/dai-luong-nao-sau-day-tang-gap-doi-khi-tang-gap-doi-bien-do-dao-dong-dieu-hoa-cua-co-10487065",
            group: "Trắc nghiệm",
          },
          {
            title: "Video Đại cương về dao động điều hòa",
            url: "https://tuyensinh247.com/bai-giang-dai-cuong-ve-dao-dong-dieu-hoa-v38761.html",
            group: "Video bài giảng",
          },
        ],
      },
      {
        slug: "song-co-song-am",
        title: "Sóng cơ và sóng âm",
        description:
          "Sóng cơ và sự truyền sóng, Giao thoa sóng, Sóng dừng, Sóng âm",
        topics: [
          {
            slug: "song-co-va-su-truyen-song",
            title: "Sóng cơ và sự truyền sóng",
            description: "Sóng cơ và sự truyền sóng",
            subtopics: [
              "Khái niệm sóng cơ",
              "Phương trình sóng",
              "Bước sóng",
              "Tốc độ truyền sóng",
            ],
            legacyPath: "grade12/song-co-song-am/song_co_va_su_truyen_song",
          },
          {
            slug: "giao-thoa-song",
            title: "Giao thoa sóng",
            description:
              "Gọi d₁ = S₁M, d₂ = S₂M là khoảng cách từ M đến hai nguồn.",
            subtopics: [
              "Hiện tượng giao thoa",
              "Hai nguồn kết hợp",
              "Vân giao thoa",
              "Điều kiện cực đại, cực tiểu",
            ],
            legacyPath: "grade12/song-co-song-am/giao_thoa_song",
          },
          {
            slug: "song-dung",
            title: "Sóng dừng",
            description: "Trong đó a là biên độ sóng tới (và sóng phản xạ)",
            subtopics: [
              "Phản xạ sóng",
              "Sóng dừng trên dây",
              "Điều kiện có sóng dừng",
              "Ứng dụng",
            ],
            legacyPath: "grade12/song-co-song-am/song_dung",
          },
          {
            slug: "song-am",
            title: "Sóng âm",
            description: "Sóng âm",
            subtopics: [
              "Đặc trưng vật lý",
              "Đặc trưng sinh lý",
              "Cường độ âm",
              "Mức cường độ âm",
            ],
            legacyPath: "grade12/song-co-song-am/song_am",
          },
          {
            slug: "hieu-ung-doppler",
            title: "Hiệu ứng Doppler",
            description: "Hiệu ứng Doppler",
            subtopics: [
              "Nguồn âm chuyển động",
              "Người nghe chuyển động",
              "Công thức Doppler",
              "Ứng dụng",
            ],
            legacyPath: "grade12/song-co-song-am/hieu_ung_doppler",
          },
        ],
        links: [
          {
            title: "Giao thoa sóng",
            url: "https://www.vietjack.com/giai-bai-tap-vat-ly-12/chuong-2-song-co-va-song-am.jsp",
            group: "Lý thuyết",
          },
          {
            title: "Sóng dừng",
            url: "https://hoc247.net/on-tap-vat-ly-12-chuong-2-song-co-index.html",
            group: "Lý thuyết",
          },
          {
            title: "Hiệu ứng doppler",
            url: "https://vi.wikipedia.org/wiki/Hiệu_ứng_Doppler",
            group: "Lý thuyết",
          },
          {
            title: "Hệ thống công thức Vật Lý 12 - Chương 2",
            url: "https://tailieugiangday.vn/item/he-thong-cong-thuc-vat-ly-12-chuong-2-song-am-va-song-co/5025",
            group: "Công thức",
          },
          {
            title:
              "Bài Tập Trắc Nghiệm Vật Lý 12: Chương Sóng Cơ - Sóng Âm (Có Đáp Án)",
            url: "https://www.kienguru.vn/blog/bai-tap-trac-nghiem-vat-ly-12-song-co-song-am",
            group: "Bài tập",
          },
          {
            title: "Chuyên đề sóng cơ bài tập và đáp án",
            url: "https://www.slideshare.net/thangtmc73/chuyn-song-c-bai-tp-va-ap-an",
            group: "Bài tập",
          },
          {
            title: "Vật Lý 12 - Chương 2: Sóng Cơ Và Sóng Âm",
            url: "https://lythayquan.vn/khoa-hoc/65/2006-vat-ly-12-chuong-2-song-co-va-song-am",
            group: "Video bài giảng",
          },
          {
            title: "Tóm tắt lý thuyết Vật lý 12",
            url: "https://baigiangvatlydotnet.wordpress.com/tom-tat-ly-thuyet/",
            group: "Tài liệu bổ sung",
          },
          {
            title: "Tóm tắt chương trình học môn Vật lý 12",
            url: "https://amcollege.edu.vn/tom-tat-chuong-trinh-hoc-mon-vat-ly-12/",
            group: "Tài liệu bổ sung",
          },
        ],
      },
      {
        slug: "dien-xoay-chieu",
        title: "Điện xoay chiều",
        description:
          "Đại cương về dòng điện xoay chiều, Các mạch điện xoay chiều, Công suất điện, Máy biến áp và truyền tải điện năng",
        topics: [
          {
            slug: "bai-1-dai-cuong-dong-dien-xoay-chieu",
            title: "Đại cương về dòng điện xoay chiều",
            description:
              "Tìm hiểu về nguyên tắc tạo ra dòng điện xoay chiều, các đại lượng đặc trưng và giá trị hiệu dụng. Cơ sở của mọi thiết bị điện trong đời sống.",
            subtopics: [
              "Nguyên tắc tạo ra",
              "Giá trị hiệu dụng",
              "Biểu diễn bằng vectơ quay",
              "Phương trình",
            ],
            legacyPath:
              "grade12/dien-xoay-chieu/bai-1-dai-cuong-dong-dien-xoay-chieu",
          },
          {
            slug: "bai-2-cac-mach-dien-xoay-chieu",
            title: "Các mạch điện xoay chiều",
            description:
              "Tìm hiểu về các loại mạch điện xoay chiều: mạch thuần trở R, thuần cảm L, thuần dung C và mạch RLC nối tiếp. Phân tích tổng trở và độ lệch pha.",
            subtopics: ["Mạch R", "Mạch L", "Mạch C", "Mạch RLC nối tiếp"],
            legacyPath:
              "grade12/dien-xoay-chieu/bai-2-cac-mach-dien-xoay-chieu",
          },
          {
            slug: "bai-3-cong-suat-dien-xoay-chieu",
            title: "Công suất điện xoay chiều",
            description:
              "Tìm hiểu về công suất tiêu thụ trong mạch điện xoay chiều, hệ số công suất cosφ, công suất tác dụng, phản kháng và biện pháp nâng cao hệ số công suất.",
            subtopics: [
              "Công suất tức thời",
              "Công suất trung bình",
              "Hệ số công suất",
              "Nâng cao hệ số công suất",
            ],
            legacyPath:
              "grade12/dien-xoay-chieu/bai-3-cong-suat-dien-xoay-chieu",
          },
          {
            slug: "bai-4-may-bien-ap-truyen-tai-dien-nang",
            title: "Máy biến áp và truyền tải điện năng",
            description:
              "Tìm hiểu về cấu tạo, nguyên lý hoạt động của máy biến áp và ứng dụng trong truyền tải điện năng đi xa. Phân tích cách giảm hao phí điện năng.",
            subtopics: [
              "Cấu tạo máy biến áp",
              "Nguyên lý hoạt động",
              "Truyền tải điện năng",
              "Hiệu suất truyền tải",
            ],
            legacyPath:
              "grade12/dien-xoay-chieu/bai-4-may-bien-ap-truyen-tai-dien-nang",
          },
        ],
        links: [],
      },
      {
        slug: "dao-dong-dien-tu",
        title: "Dao động điện từ",
        description: "Mạch dao động LC, Điện từ trường, Sóng điện từ",
        topics: [
          {
            slug: "bai-1-mach-dao-dong-lc",
            title: "Mạch dao động LC",
            description:
              "Mạch dao động LC là mạch điện gồm tụ điện và cuộn cảm. Tìm hiểu về nguyên lý hoạt động, phương trình dao động điện từ và năng lượng trong mạch LC.",
            subtopics: [
              "Mạch dao động",
              "Dao động điện từ tự do",
              "Năng lượng điện từ",
              "Chu kỳ, tần số",
            ],
            legacyPath: "grade12/dao-dong-dien-tu/bai-1-mach-dao-dong-lc",
          },
          {
            slug: "bai-2-dien-tu-truong",
            title: "Điện từ trường",
            description:
              "Điện từ trường là sự thống nhất giữa điện trường và từ trường. Tìm hiểu về thuyết điện từ Maxwell, mối liên hệ giữa điện trường và từ trường biến thiên.",
            subtopics: [
              "Điện trường biến thiên",
              "Từ trường biến thiên",
              "Điện từ trường",
              "Thuyết Maxwell",
            ],
            legacyPath: "grade12/dao-dong-dien-tu/bai-2-dien-tu-truong",
          },
          {
            slug: "bai-3-song-dien-tu",
            title: "Sóng điện từ",
            description:
              "Sóng điện từ là điện từ trường lan truyền trong không gian. Tìm hiểu về tính chất, cách tạo ra, thu sóng điện từ và ứng dụng trong truyền thông không dây.",
            subtopics: [
              "Đặc điểm sóng điện từ",
              "Thang sóng điện từ",
              "Truyền thông tin",
              "Ứng dụng",
            ],
            legacyPath: "grade12/dao-dong-dien-tu/bai-3-song-dien-tu",
          },
        ],
        links: [],
      },
      {
        slug: "song-anh-sang",
        title: "Sóng ánh sáng",
        description: "Tán sắc ánh sáng, Giao thoa ánh sáng, Quang phổ",
        topics: [
          {
            slug: "bai-1-tan-sac-anh-sang",
            title: "Tán sắc ánh sáng",
            description:
              "Tán sắc ánh sáng là hiện tượng phân tích ánh sáng trắng thành các ánh sáng đơn sắc. Tìm hiểu về lăng kính, chiết suất và các ứng dụng của tán sắc.",
            subtopics: [
              "Hiện tượng tán sắc",
              "Ánh sáng trắng",
              "Chiết suất",
              "Quang phổ",
            ],
            legacyPath: "grade12/song-anh-sang/bai-1-tan-sac-anh-sang",
          },
          {
            slug: "bai-2-giao-thoa-anh-sang",
            title: "Giao thoa ánh sáng",
            description:
              "Giao thoa ánh sáng là hiện tượng đặc trưng chứng tỏ ánh sáng có tính chất sóng. Tìm hiểu về thí nghiệm Young, vân giao thoa và các ứng dụng.",
            subtopics: [
              "Thí nghiệm Young",
              "Vân giao thoa",
              "Khoảng vân",
              "Ánh sáng đơn sắc",
            ],
            legacyPath: "grade12/song-anh-sang/bai-2-giao-thoa-anh-sang",
          },
          {
            slug: "bai-3-nhieu-xa-anh-sang",
            title: "Nhiễu xạ ánh sáng",
            description:
              "Nhiễu xạ ánh sáng là hiện tượng ánh sáng lệch khỏi phương truyền thẳng khi gặp vật cản. Tìm hiểu về nguyên lý Huygens-Fresnel và các ứng dụng.",
            subtopics: [
              "Hiện tượng nhiễu xạ",
              "Nhiễu xạ qua khe hẹp",
              "Cách tử nhiễu xạ",
              "Ứng dụng",
            ],
            legacyPath: "grade12/song-anh-sang/bai-3-nhieu-xa-anh-sang",
          },
          {
            slug: "bai-4-quang-pho",
            title: "Quang phổ",
            description:
              "Quang phổ là tập hợp các bức xạ đơn sắc của một nguồn sáng. Tìm hiểu về các loại quang phổ, máy quang phổ và ứng dụng trong phân tích vật chất.",
            subtopics: [
              "Quang phổ liên tục",
              "Quang phổ vạch",
              "Quang phổ hấp thụ",
              "Phân tích quang phổ",
            ],
            legacyPath: "grade12/song-anh-sang/bai-4-quang-pho",
          },
        ],
        links: [],
      },
      {
        slug: "luong-tu-anh-sang",
        title: "Lượng tử ánh sáng",
        description: "Hiện tượng quang điện, Thuyết lượng tử ánh sáng, Laze",
        topics: [
          {
            slug: "bai-2-hien-tuong-quang-dien-trong",
            title: "Hiện tượng quang điện trong",
            description:
              "Tìm hiểu về hiện tượng quang điện trong, quang dẫn, pin quang điện, quang trở và các ứng dụng trong công nghệ hiện đại.",
            subtopics: [
              "Chất quang dẫn",
              "Quang điện trở",
              "Pin quang điện",
              "Ứng dụng",
            ],
            legacyPath:
              "grade12/luong-tu-anh-sang/bai-2-hien-tuong-quang-dien-trong",
          },
          {
            slug: "bai-3-quang-pho-vach-nguyen-tu-hydro",
            title: "Quang phổ vạch nguyên tử hydro",
            description:
              "Tìm hiểu về mẫu nguyên tử Bohr, quang phổ vạch của hydro, các dãy quang phổ Lyman, Balmer, Paschen và ứng dụng trong thiên văn học.",
            subtopics: [
              "Mẫu nguyên tử Bohr",
              "Quang phổ hydro",
              "Các dãy quang phổ",
              "Năng lượng ion hóa",
            ],
            legacyPath:
              "grade12/luong-tu-anh-sang/bai-3-quang-pho-vach-nguyen-tu-hydro",
          },
          {
            slug: "bai-4-hien-tuong-quang-phat-quang-laser",
            title: "Hiện tượng quang phát quang - Laser",
            description:
              "Tìm hiểu về hiện tượng phát quang, huỳnh quang, lân quang, nguyên lý hoạt động của laser và các ứng dụng trong đời sống, y học, công nghiệp.",
            subtopics: [
              "Huỳnh quang",
              "Lân quang",
              "Nguyên lý laser",
              "Ứng dụng laser",
            ],
            legacyPath:
              "grade12/luong-tu-anh-sang/bai-4-hien-tuong-quang-phat-quang-laser",
          },
        ],
        links: [],
      },
      {
        slug: "hat-nhan-nguyen-tu",
        title: "Hạt nhân nguyên tử",
        description:
          "Tính chất và cấu tạo hạt nhân, Năng lượng liên kết, Phóng xạ, Phản ứng hạt nhân",
        topics: [
          {
            slug: "bai-1-tinh-chat-va-cau-tao-hat-nhan",
            title: "Tính chất và cấu tạo hạt nhân",
            description:
              "Tìm hiểu về cấu tạo hạt nhân nguyên tử, các hạt cơ bản proton và neutron, kích thước hạt nhân và các đại lượng đặc trưng của hạt nhân.",
            subtopics: [
              "Cấu tạo hạt nhân",
              "Ký hiệu hạt nhân",
              "Đồng vị",
              "Đơn vị khối lượng nguyên tử",
            ],
            legacyPath:
              "grade12/hat-nhan-nguyen-tu/bai-1-tinh-chat-va-cau-tao-hat-nhan",
          },
          {
            slug: "bai-2-nang-luong-lien-ket-hat-nhan",
            title: "Năng lượng liên kết hạt nhân",
            description:
              "Tìm hiểu về độ hụt khối, năng lượng liên kết hạt nhân, năng lượng liên kết riêng và độ bền vững của hạt nhân. Hệ thức Einstein E=mc².",
            subtopics: [
              "Độ hụt khối",
              "Năng lượng liên kết",
              "Năng lượng liên kết riêng",
              "Độ bền hạt nhân",
            ],
            legacyPath:
              "grade12/hat-nhan-nguyen-tu/bai-2-nang-luong-lien-ket-hat-nhan",
          },
          {
            slug: "bai-3-phong-xa",
            title: "Phóng xạ",
            description:
              "Tìm hiểu về hiện tượng phóng xạ, các loại tia phóng xạ, định luật phân rã phóng xạ, chu kỳ bán rã và ứng dụng của phóng xạ trong đời sống.",
            subtopics: [
              "Định luật phóng xạ",
              "Chu kỳ bán rã",
              "Các tia phóng xạ",
              "Ứng dụng phóng xạ",
            ],
            legacyPath: "grade12/hat-nhan-nguyen-tu/bai-3-phong-xa",
          },
          {
            slug: "bai-4-phan-ung-hat-nhan",
            title: "Phản ứng hạt nhân",
            description:
              "Tìm hiểu về phản ứng hạt nhân, các định luật bảo toàn, phản ứng phân hạch, phản ứng nhiệt hạch và ứng dụng trong năng lượng hạt nhân.",
            subtopics: [
              "Phản ứng hạt nhân",
              "Định luật bảo toàn",
              "Phân hạch",
              "Nhiệt hạch",
            ],
            legacyPath: "grade12/hat-nhan-nguyen-tu/bai-4-phan-ung-hat-nhan",
          },
        ],
        links: [],
      },
    ],
  },
];
