/**
 * S8-03: v1's handout gallery (`public/lesson_handout/*.jpg`, ~12 MB) as
 * WebP for `/gallery`. One-off, output committed:
 *
 *   node scripts/convert-gallery.ts ../onluyenvatly
 *
 * Writes `public/gallery/<n>.webp` (≤ 1600 px, for reading) and
 * `public/gallery/<n>-thumb.webp` (480 px wide, for the grid), plus
 * `src/content/gallery.ts` with each image's size so the page can reserve
 * space (no layout shift). Order is v1's numeric file order.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import sharp from "sharp";

const v1Root = process.argv[2];
if (!v1Root) {
  console.error("Usage: node scripts/convert-gallery.ts <path to v1 repo>");
  process.exit(1);
}
const SOURCE = join(v1Root, "public", "lesson_handout");
const OUT = join("public", "gallery");

const files = readdirSync(SOURCE)
  .filter((f) => /\.(jpe?g|png|gif)$/i.test(f))
  .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

type Item = {
  src: string;
  thumb: string;
  width: number;
  height: number;
  thumbWidth: number;
  thumbHeight: number;
};
const items: Item[] = [];
let after = 0;

for (const [i, file] of files.entries()) {
  const n = i + 1;
  const input = sharp(join(SOURCE, file)).rotate(); // honour EXIF orientation
  const full = await input
    .clone()
    .resize({
      width: 1600,
      height: 1600,
      fit: "inside",
      withoutEnlargement: true,
    })
    .webp({ quality: 80 })
    .toBuffer({ resolveWithObject: true });
  const thumb = await input
    .clone()
    .resize({ width: 480, withoutEnlargement: true })
    .webp({ quality: 70 })
    .toBuffer({ resolveWithObject: true });
  writeFileSync(join(OUT, `${n}.webp`), full.data);
  writeFileSync(join(OUT, `${n}-thumb.webp`), thumb.data);
  after += full.data.length + thumb.data.length;
  items.push({
    src: `/gallery/${n}.webp`,
    thumb: `/gallery/${n}-thumb.webp`,
    width: full.info.width,
    height: full.info.height,
    thumbWidth: thumb.info.width,
    thumbHeight: thumb.info.height,
  });
  console.log(
    `${basename(file)} → ${n}.webp ${full.info.width}×${full.info.height}`,
  );
}

writeFileSync(
  join("src", "content", "gallery.ts"),
  `// Generated by scripts/convert-gallery.ts from v1 public/lesson_handout (S8-03).
export type GalleryItem = {
  src: string;
  thumb: string;
  width: number;
  height: number;
  thumbWidth: number;
  thumbHeight: number;
};

export const gallery: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`,
);
console.log(
  `${items.length} images, ${(after / 1e6).toFixed(1)} MB of WebP (full + thumbnails).`,
);
